version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm i -g yarn
      - yarn install
  build:
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/build
cache:
  paths:
    - yarn.lock
