version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm i -g yarn
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/build
      - aws s3 cp . s3://$BUCKET_WEB/ --recursive
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/build
cache:
  paths:
    - yarn.lock
